# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, null=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard_app.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
